### PR TITLE
Feat: Added `firstMatchOnly` parameter

### PR DESCRIPTION
**Pull request by shibupanda**
Added  `firstMatchOnly` according to flutter driver doc.
https://api.flutter.dev/flutter/flutter_driver/CommonFinders/ancestor.html
https://api.flutter.dev/flutter/flutter_driver/Descendant-class.html

### CODE REVIEW

**Comment by KazuCocoa** [comment]
Does this work?
I haven't tested it, but this works well, then I can release Ruby and Python libraries.
@shibupanda

**Comment by shibupanda** [comment]
@KazuCocoa we can merge this PR and same we can add for other library.

**Comment by KazuCocoa** [comment]
Ok. Could you merge the current master to this branch?
I've set up GitHub actions for Python, Ruby and NodeJS.

**Comment by KazuCocoa** [comment]
let me merge this and see the tests

**Pull request merged**
