### PR TITLE
feat: click element with timeout 

### PR DESCRIPTION
**Pull request by thuonglai**

### CODE REVIEW

**Comment by thuonglai** [comment]
@KazuCocoa  can you check it help me. And maybe merge it for me. Thanks

**Review by KazuCocoa — APPROVED** [review]

**Comment by thuonglai** [comment]
@KazuCocoa . Can you merge it and build new version for it. Thanks

**Comment by KazuCocoa** [comment]
Don't worry. I'll do but maybe this repo needs to update some code in JS. The merge will be after confirming current code can build with latest appium dependencies

**Comment by KazuCocoa** [comment]
1.16.0 has this

**Pull request merged**
