### PR TITLE
update readme to add some steps and clarity

### PR DESCRIPTION
**Pull request by prolificcoder**
Addressing https://github.com/appium-userland/appium-flutter-driver/issues/249

### CODE REVIEW

**Comment by prolificcoder** [comment]
Oh thank you for accepting. In the next few days/weeks I will be spending some time on figuring appium driver out and would love to get some of your thoughts and feedback.

**Comment by prolificcoder** [comment]
Also a question for language bindings, though I am from kotlin background I was thinking to explore nodejs because appium itself is nodejs but if you have a recommendation on any other language that has more usage, would be open to that suggestion.

**Comment by KazuCocoa** [comment]
You could use https://github.com/KazuCocoa/appium_dart if you'd like to add tests in Dart to make test code language the same as production code. I frequently use Ruby, Python and kind of webdriverio. I haven't used Java and .NET client so much (but this includes my personal preference)

Appium itself is in NodeJS, but generally, it is a standalone server that is managed via CLI. When you dig into Appium to investigate some cause, you may need to read/write NodeJS, Obj-C (iOS), and Java/Kotlin (Android), but they are independent of your decision about what kind of languages you'd like to add tests.

**Comment by prolificcoder** [comment]
Oh you wrote the Dart bindings too! awesome! Since the production code and other tests are in dart and the future app would also be fully dart, it would be great if we can make Dart work. 

I looked a bit at that repo looks like only a subset of commands are supported, also in the examples for automation name there isn't [FLUTTER](https://github.com/KazuCocoa/appium_dart/blob/main/test/functional/helper.dart#L10). But that looked like your personal project and not sure how many folks would contribute to dart appium bindings. Will look into it a bit more deeply and again thank you for all the work.

**Comment by KazuCocoa** [comment]
Appium clients are for Appium framework. So the `automationName` does not matter if the automationName modules (appium server side) follow the expected protocol.
https://github.com/KazuCocoa/appium_dart/blob/9a5d3f840620c7003d213d1246f5cb8a703d3172/test/unit/flutter_finder_test.dart is only the Flutter driver-specific in the client.

**Pull request merged**
