### PR TITLE
feat: Use waitForTappable in scrollUntilVisible method

### LINKED ISSUE #301: scrollUntilVisible uses `waitFor` that ignores interaction
Hi!
Current implementation of `scrollUntilVisible` uses `waitFor` for making sure that a widget is visible. The issue is that `waitFor` doesn't ensure us about that, because it only waits for the widget to be available in the widget tree. The result is that the scroll stops, the widget can be out of the viewport and we can't tap on it.

So my suggestion is why don't we use `waitForTappable` in this context?

### PR DESCRIPTION
**Pull request by mateuszwojtczak**
Resolves #301

### CODE REVIEW

**Review by KazuCocoa — APPROVED** [review]
looks good to me..

**Comment by KazuCocoa** [comment]
thank you!

**Comment by KazuCocoa** [comment]
fyi: v1.9.0 uses `scrollUntilTapable` for this `waitForTappable`. Instead, `scrollUntilVisible` uses `waitFor`

**Comment by giangthao** [comment]
Hello KazuCocoa, how can I add latest version to use by maven in Java ?

**Comment by KazuCocoa** [comment]
This driver is available via npm in NodeJS, not Java. If you mean client's Finder, then https://github.com/appium-userland/appium-flutter-driver#java-implementation may help

**Comment by giangthao** [comment]
Thanks

**Pull request merged**
